spring:
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size:  10240 #单个数据的大小
      max-request-size: 10240 #总数据的大小
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

swagger:
  enable: true

server:
  tomcat:
    threads:
      max: 300
    max-connections: 4000