spring:
  cache:
    #指定缓存类型为redis
    type: redis
  #redis依赖
  redis:
    redisson:
      # 配置文件，默认classpath
      #类型:cluster（集群），single（单机），sentinel（哨兵）
#      type: cluster
      #redis的地址，格式：redis://ip:port  如果是集群和哨兵，多个地址的情况下用，隔开
#      address: redis://127.0.0.1:7001,redis://127.0.0.1:7002,redis://127.0.0.1:7003,redis://127.0.0.1:7004,
#               redis://127.0.0.1:7005,redis://127.0.0.1:7006
      #密码，没有就设置null
#      password: 123456
      #主节点名称，这里只针对哨兵模式有用
#      masterName: mymaster
#    cluster:
#      #      集群重定向次数
#      max-redirects: 3
#      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006,127.0.0.1:7007,127.0.0.1:7008,127.0.0.1:7009
#    password: 123456
#    timeout: 20000
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 50000
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 1000
#        # 连接池中的最小空闲连接
#        min-idle: 50