#如果是mybatis-plus配置如下
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      #      field-strategy: not_empty
      table-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/**/*.xml
  #在mapper.xml中可以使用别名而不使用类的全路径名
  #type-aliases-package: com.lcy.mybatis.entity
